### ISSUE TITLE
Change baud rate for the serial monitor

### ISSUE THREAD

**Issue by JohnDoeKyrgyz** [formulahendry/vscode-platformio#3]
Is it possible to change the baud rate for the serial monitor?

**Comment by formulahendry** [comment]
Hi @JohnDoeKyrgyz , currently, there is no direct way to change the baud rate, it is always 9600 for now. I plan to add a config entry in `File` > `Preferences` -> `Settings`, so that users could change the baud rate there. What's your opinion? Or, will you change the baud rate frequently and want this extension to provide a UI (e.g. in Status Bar at the bottom) to change the baud rate?

**Comment by JohnDoeKyrgyz** [comment]
I think the File > Preferences > Settings entry is a good idea. In many examples I see people using 115200 as the default baud rate for serial communication.

Would it also be possible to configure this on a per device basis? Maybe a custom setting in the platformio.ini file?

**Comment by formulahendry** [comment]
> per device basis

Do you mean:
* baud rate would be different per workspace?
* Or, baud rate  would be different per device but in the same workspace? i.e. there are several devices in the same platformio.ini but have different baud rate

**Comment by JohnDoeKyrgyz** [comment]
Ideally it would be possible to have one baud rate setting for the entire workspace that would be the default, and then the ability to override it for each device.

Realistically though, just being able to change the baud rate in File > Preferences > Settings would probably be good enough.

**Comment by formulahendry** [comment]
Thanks for your feedback! That makes complete sense. Realistically, I will add a config entry in `File` > `Preferences` -> `Settings`, so that user could set baud rate in the overall User Settings as well as in each Workspace Settings.

**Comment by formulahendry** [comment]
Hi @JohnDoeKyrgyz , a config entry `platformio.baudRate` is added, please install the latest version and have a try. Let me know if you have any other feedback.

**Comment by JohnDoeKyrgyz** [comment]
Thanks! This will be useful. Looks good to me.

**Comment by egur** [comment]
Hi,

I would like to use a BaudRate  > 921600 bps.
How can it be done ?
I would like to set the BaudRate to be larger than 3 MB

Please advise.

**Comment by formulahendry** [comment]
@egur Does updating `platformio.baudRate` work for you?

**Comment by RAVURIVENKAT** [comment]
please send related answer for how to change baudrate in serial communication

**Comment by ArtiomLK** [comment]
In the file _**platformio.ini**_ add:
`monitor_speed = baudRate`
For example:
`monitor_speed = 115200`
