### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by neilyoung** [formulahendry/vscode-platformio#4]
Great little tool. Has substituted my own task.json nearly completely. Could you provide a hint, how to run BUILD and UPLOAD one after the other with one stroke?

Thanks

**Comment by formulahendry** [comment]
Hi @neilyoung , do you want to run `Build` then `Upload` with just one click/command?

**Comment by neilyoung** [comment]
@formulahendry Yes, this would be the intention. Ideally also followed by the DISPLAY command

**Comment by neilyoung** [comment]
PS: I suppose this can be done with any other trick in VSCode too, but I would prefer to have it out of your tool. Kind of Build, Upload and Serial Monitor in one piece.

**Comment by formulahendry** [comment]
Got it. I will provide a command with combined `Build`, `Upload` and `Open Serial Monitor`.

**Comment by formulahendry** [comment]
@neilyoung , just publish the latest version, please install and have a try. Use shortcut `Ctrl+Alt+A`, or press `F1` and then select/type `PlatformIO: Build, Upload and Open Serial Monitor`. Let me know if it works as you expected.

**Comment by neilyoung** [comment]
@formulahendry Like a charm. Many thanks. Very, very useful to speed up development cycles.

Thanks!

**Comment by formulahendry** [comment]
You are welcome~

**Comment by neilyoung** [comment]
Maybe for one of the next releases: To have it in the right click menu too would be super gold. But just if nothing else has to be done...

**Comment by formulahendry** [comment]
I just want to not put too many commands in context menu to make the menu too long. But I will consider that. Maybe an icon in bottom Status Bar? 
![image](https://cloud.githubusercontent.com/assets/1050213/25654274/0c22ebea-3023-11e7-896f-0c21d041171b.png)

**Comment by neilyoung** [comment]
Also ok for me. I just thought it, because you have all your other commands in the menu. Not an issue, really. I'm fine with the short cut.

**Comment by formulahendry** [comment]
Hi @neilyoung , I have added icon in bottom Status Bar. You could install the latest version and have a try.

![builduploadandopenserialmonitor](https://cloud.githubusercontent.com/assets/1050213/25882335/6f70f4ce-3575-11e7-9b32-25b1e216cbd8.png)

**Comment by neilyoung** [comment]
@formulahendry Yepp, thanks. Works great.
