### ISSUE TITLE
Add C/C++ extension as an extension dependency

### ISSUE THREAD

**Issue by formulahendry** [formulahendry/vscode-platformio#8]
I wonder whether it would be better to add C/C++ extension as an extension dependency. i.e. put below settings into package.json. Installing PlatformIO extension will also install the C/C++ extension.
```json
"extensionDependencies": [
    "ms-vscode.cpptools"
]
```
There seems no side effect.

**Comment by dymo** [comment]
I think it is a very good idea. Then we can also remove the check if the extension is installed in in ```configureAutoUpdateIncludes()```.

**Comment by formulahendry** [comment]
There is no side effect to keep the check, and also avoid the corner case: user manually uninstalls the C/C++ extension.
